load("//build/kernel/kleaf:kernel.bzl", "ddk_headers")
load("//soc-repo:configs/ext_config/moto_consolidate_config.bzl", "moto_consolidate_config")

_wonder_enabled = moto_consolidate_config.get("CONFIG_WONDER_SUPPORT") == "y"

ddk_headers(
    name = "wlan_uapi_headers",
    hdrs = glob([
        "uapi/linux/*.h"
    ]),
    includes = ["uapi/linux"]
)

config_setting(
    name = "wonder_enabled",
    define_values = {
        "CONFIG_WONDER_SUPPORT": "y",
    },
)

load(":wlan_qcacld3_modules.bzl", "define_modules")

package(
    default_visibility = [
        "//visibility:public",
    ],
)

define_modules(wonder_enabled = _wonder_enabled)
